
CREATE TABLE miningnow_asics (
    asic_slug VARCHAR(200) NOT NULL, 
    asic_id VARCHAR(200) NOT NULL, 
    hash_rate_type_title VARCHAR(200), 
    hash_rate_type VARCHAR(200), 
    hash_rate_unit VARCHAR(200), 
    brand_title VARCHAR(200), 
    algo_title VARCHAR(200), 
    noise VARCHAR(200), 
    title VARCHAR(200), 
    description VARCHAR(1000), 
    algo_id VARCHAR(200), 
    hash_rate FLOAT, 
    hash_rate_type_id VARCHAR(200), 
    power_watts FLOAT, 
    weight_kg FLOAT, 
    announcement_date VARCHAR(200), 
    launch_date VARCHAR(200), 
    price_index_enable BOOLEAN, 
    reported_created_at VARCHAR(200), 
    reported_updated_at VARCHAR(200), 
    note VARCHAR(200), 
    cooling VARCHAR(200), 
    best_price_usd FLOAT, 
    efficiency_value FLOAT, 
    efficiency_unit VARCHAR(200), 
    brand_image_light_url VARCHAR(1000), 
    brand_image_dark_url VARCHAR(1000), 
    brand_icon_light_url VARCHAR(1000), 
    brand_icon_dark_url VARCHAR(1000), 
    image_url VARCHAR(1000), 
    reference_link_url VARCHAR(1000), 
    created_at DATETIME DEFAULT now() NOT NULL, 
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (asic_slug)
)

