
CREATE TABLE wheretomine_coins (
    coin_name VARCHAR(100) NOT NULL, 
    coin_abbreviation VARCHAR(20) NOT NULL, 
    coin_slug VARCHAR(100) NOT NULL, 
    description VARCHAR(5000), 
    website_link VARCHAR(500), 
    explorer_link VARCHAR(500), 
    subpool_count BIGINT NOT NULL, 
    network_hashrate FLOAT NOT NULL, 
    network_difficulty FLOAT NOT NULL, 
    block_reward FLOAT NOT NULL, 
    block_time FLOAT NOT NULL, 
    height INTEGER NOT NULL, 
    price_btc FLOAT NOT NULL, 
    price_usd FLOAT NOT NULL, 
    volume_24h FLOAT NOT NULL, 
    percentage_change_24h FLOAT NOT NULL, 
    market_cap FLOAT NOT NULL, 
    status VARCHAR(50), 
    is_gathering BOOLEAN NOT NULL, 
    is_lagging BOOLEAN NOT NULL, 
    is_testing BOOLEAN NOT NULL, 
    is_listed BOOLEAN NOT NULL, 
    is_sponsored BOOLEAN NOT NULL, 
    has_calculator BOOLEAN NOT NULL, 
    reported_last_updated DATETIME NOT NULL, 
    algorithm_name VARCHAR(100) NOT NULL, 
    algorithm_type VARCHAR(100) NOT NULL, 
    algorithm_slug VARCHAR(100) NOT NULL, 
    links_json VARCHAR(3000), 
    created_at DATETIME DEFAULT now() NOT NULL, 
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
)

