name: Run Scripts

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  # Also run weekly.
  schedule:
    - cron: "20 12 * * 4"

jobs:
  validate-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Sync dependencies
        run: uv sync --all-groups

      - name: Ruff lint
        run: uv run ruff check .

      - name: Ruff format check
        run: uv run ruff format . --check

      - name: Pyright check
        run: uv run pyright .

      - name: Pytest
        run: uv run pytest tests/

  run-minerstat-update:
    runs-on: ubuntu-latest
    needs: validate-job
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Sync dependencies
        run: uv sync --all-groups

      - name: Install dolt
        run: sudo bash -c 'curl -L https://github.com/dolthub/dolt/releases/latest/download/install.sh | sudo bash'

      - name: Import Dolt credentials
        run: |
          echo "$DOLTHUB_LOGIN_JWT_CONTENTS" > dolt_jwt.json
          dolt creds import dolt_jwt.json
        env:
          DOLTHUB_LOGIN_JWT_CONTENTS: ${{ secrets.DOLTHUB_LOGIN_JWT_CONTENTS }}
          
      - name: Run Minerstat data pipeline
        run: |
          uv run src/coin_profitability_scraper/minerstat/minerstat_pipeline.py

  run-cryptoslate-update:
    runs-on: ubuntu-latest
    needs: validate-job
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Sync dependencies
        run: uv sync --all-groups

      - name: Install dolt
        run: sudo bash -c 'curl -L https://github.com/dolthub/dolt/releases/latest/download/install.sh | sudo bash'
      
      - name: Import Dolt credentials
        run: |
          echo "$DOLTHUB_LOGIN_JWT_CONTENTS" > dolt_jwt.json
          dolt creds import dolt_jwt.json
        env:
          DOLTHUB_LOGIN_JWT_CONTENTS: ${{ secrets.DOLTHUB_LOGIN_JWT_CONTENTS }}

      - name: Run Crypto Slate data pipeline
        run: |
          uv run src/coin_profitability_scraper/crypto_slate/crypto_slate_pipeline.py

  run-miningnow-update:
    runs-on: ubuntu-latest
    needs: validate-job
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Sync dependencies
        run: uv sync --all-groups

      - name: Install dolt
        run: sudo bash -c 'curl -L https://github.com/dolthub/dolt/releases/latest/download/install.sh | sudo bash'
      
      - name: Import Dolt credentials
        run: |
          echo "$DOLTHUB_LOGIN_JWT_CONTENTS" > dolt_jwt.json
          dolt creds import dolt_jwt.json
        env:
          DOLTHUB_LOGIN_JWT_CONTENTS: ${{ secrets.DOLTHUB_LOGIN_JWT_CONTENTS }}

      - name: Run MiningNow data pipeline
        run: |
          uv run src/coin_profitability_scraper/miningnow/miningnow_pipeline.py
